version: 0.2

phases:
  pre_build:
    commands:
      - echo *** Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 135044555678.dkr.ecr.us-east-2.amazonaws.com
      # - pip install -r requirements.txt
  build:
    commands:
      - echo *** Running tests...
      - docker build -t devops/goku .
      - docker run devops/goku python -m unittest
      - docker tag devops/goku:latest 135044555678.dkr.ecr.us-east-2.amazonaws.com/devops/goku:latest
  post_build:
    commands:
      - echo *** Build completed on `date`
      - docker push 135044555678.dkr.ecr.us-east-2.amazonaws.com/devops/goku:latest
      - echo *** Pushed image to ECR
      - printf '[{"name":"container-black-list","imageUri":"135044555678.dkr.ecr.us-east-2.amazonaws.com/devops/goku:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"135044555678.dkr.ecr.us-east-2.amazonaws.com/devops/goku:latest"}' > imageDetail.json
      - cat imagedefinitions.json

artifacts:
  files:
    - "**/*"
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.json
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
